services:
  app:
    depends_on:
      - mysql
    image: car-sharing
    restart: no
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    build: .
    env_file: .env
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.driver-class-name" : "$MYSQL_DRIVER",
      "spring.datasource.url" : "jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?serverTimeZone=UTC&createDatabaseIfNotExist=true",
      "spring.datasource.username" : "$MYSQL_ROOT_USER",
      "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD"
      }'

  mysql:
    image: mysql:8.0
    restart: no
    env_file: .env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
